name: WordPress Playground PR Testing

# When to run tests.
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-deploy:
    # Name.
    name: Preview PR on WordPress Playground

    # Virtual Environment to use.
    # @see: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest

    # Define permissions for this action.
    permissions:
      contents: write
      pull-requests: write

    # Environment Variables.
    # Accessible by using ${{ env.NAME }}
    # Use ${{ secrets.NAME }} to include any GitHub Secrets in ${{ env.NAME }}
    # The base folder will always be /home/runner/work/github-repo-name/github-repo-name
    env:
      PLUGIN_SLUG: "wp-to-buffer" # The plugin's slug
      PLAYGROUND_BRANCH_NAME: "pr-playground-${{ github.event.pull_request.number }}" # The branch to create from this PR which will have the built Plugin ZIP and blueprint.json added
 
    # Steps to build and provide the Playground URL
    steps:
      # Checkout (copy) this repository's Plugin to this VM.
      - name: Checkout Plugin
        uses: actions/checkout@v4

      # Installs required packages that must be included in the Plugin
      # as specified in composer.json's "require" section.
      # "require-dev" is ignored by design, as these are only needed for
      # testing
      - name: Run Composer
        run: composer install --no-dev

      - name: Create ZIP File and Blueprint JSON
        run: |
          cat .distignore